version: '3.8'

services:
  api:
    image: marcelapsilverio/api:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./container/api:/var/www/html 
      - ./container/api/database:/var/www/html/database
    environment:
      APP_ENV: local
      APP_DEBUG: true
